on: [push]

name: AzureLoginSample
jobs:
 build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account set --subscription aad4aa3e-926e-420c-afcb-fd3aae710cc2
            az vm stop --resource-group trimu --name test
            
